# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 06da00eaf15721f93d6e8a50f67c3238a73f0cfa9d17848bc6faacf30acfbd24b896026d3ce5e3461522de49f4a9b686a5cc6ce057d721e435a1182bfeadd88e

test:
  secret_key_base: ba60526eb849c5c4ce27567061c4d590c32a93274dded64bd9eaae02195ee476f4b49b0eae1b495558f46322a63dda8ab7c62ff07e438d7219fb13d36b848b5e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
